// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuudfjcemimymaryrstf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dWRmamNlbWlteW1hcnlyc3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTMyOTYsImV4cCI6MjA2NTc4OTI5Nn0.0lEToPCK632J0pgOnKLRvmX5-sprhbQMfGXAX3FQ0jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);